import { getDb } from '../../../../lib/mongodb';
import { getCurrentUser } from '../../../../lib/auth';
import nodemailer from 'nodemailer';

export async function POST(request) {
  const currentUser = await getCurrentUser();
  if (!currentUser || !['super_admin', 'manager'].includes(currentUser.role)) {
    return Response.json({ message: 'Unauthorized' }, { status: 403 });
  }

  try {
    const body = await request.json();
    const { clientId, email, period = 'weekly' } = body;

    if (!clientId || !email) {
      return Response.json({ message: 'clientId and email required' }, { status: 400 });
    }

    // Fetch client data
    const db = await getDb();
    const { ObjectId } = await import('mongodb');
    const clientDoc = await db.collection('clients').findOne({ _id: new ObjectId(clientId) });
    if (!clientDoc) {
      return Response.json({ message: 'Client not found' }, { status: 404 });
    }

    // Fetch campaigns
    const campaigns = await db.collection('campaigns')
      .find({ clientId: new ObjectId(clientId) })
      .toArray();

    // Aggregate metrics
    let totalSpend = 0, totalImpressions = 0, totalClicks = 0, totalConversions = 0;
    campaigns.forEach(campaign => {
      (campaign.rows || []).forEach(row => {
        totalSpend += parseFloat(row['Amount spent (INR)'] || row['Amount spent'] || 0) || 0;
        totalImpressions += parseFloat(row['Impressions'] || 0) || 0;
        totalClicks += parseFloat(row['Clicks (all)'] || row['Clicks'] || 0) || 0;
        totalConversions += parseFloat(row['Results'] || row['Conversions'] || 0) || 0;
      });
    });

    const ctr = totalImpressions > 0 ? ((totalClicks / totalImpressions) * 100).toFixed(2) : 0;
    const cpc = totalClicks > 0 ? (totalSpend / totalClicks).toFixed(2) : 0;
    const cpm = totalImpressions > 0 ? ((totalSpend * 1000) / totalImpressions).toFixed(2) : 0;

    const clientName = clientDoc.companyName || clientDoc.username;
    const reportDate = new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' });

    // Build email HTML
    const html = `
      <!DOCTYPE html>
      <html>
      <head><meta charset="utf-8"><title>Sociapa Performance Report</title></head>
      <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f7fafc; margin: 0; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.1);">
          <div style="background: linear-gradient(135deg, #667eea, #764ba2); padding: 30px; text-align: center;">
            <h1 style="color: white; margin: 0; font-size: 24px;">📊 Sociapa Ads Report</h1>
            <p style="color: rgba(255,255,255,0.85); margin: 8px 0 0;">${period.charAt(0).toUpperCase() + period.slice(1)} Report · ${reportDate}</p>
          </div>
          <div style="padding: 30px;">
            <h2 style="color: #2d3748; margin-top: 0;">Client: ${clientName}</h2>
            <p style="color: #718096;">Here's your ${period} advertising performance summary:</p>
            
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin: 24px 0;">
              ${[
        { label: 'Total Spend', value: `₹${totalSpend.toLocaleString('en-IN', { maximumFractionDigits: 0 })}`, color: '#667eea' },
        { label: 'Impressions', value: totalImpressions.toLocaleString(), color: '#43e97b' },
        { label: 'Clicks', value: totalClicks.toLocaleString(), color: '#f093fb' },
        { label: 'Conversions', value: totalConversions.toLocaleString(), color: '#4facfe' },
        { label: 'CTR', value: `${ctr}%`, color: '#fa709a' },
        { label: 'CPC', value: `₹${cpc}`, color: '#fee140' },
        { label: 'CPM', value: `₹${cpm}`, color: '#30cfd0' },
        { label: 'Campaigns', value: campaigns.length, color: '#a18dfa' },
      ].map(item => `
                <div style="background: #f7fafc; border-radius: 8px; padding: 16px; border-left: 4px solid ${item.color};">
                  <p style="margin: 0; font-size: 12px; color: #718096; text-transform: uppercase; letter-spacing: 1px;">${item.label}</p>
                  <p style="margin: 4px 0 0; font-size: 22px; font-weight: 700; color: #2d3748;">${item.value}</p>
                </div>
              `).join('')}
            </div>

            <div style="background: linear-gradient(135deg, #667eea15, #764ba215); border-radius: 8px; padding: 16px; margin-top: 16px;">
              <p style="margin: 0; color: #4a5568; font-size: 14px;">
                This report was automatically generated by <strong>Sociapa Ads Dashboard</strong>. 
                Log in to view detailed analytics and campaign breakdowns.
              </p>
            </div>
          </div>
          <div style="background: #f7fafc; padding: 20px; text-align: center; color: #a0aec0; font-size: 12px;">
            © ${new Date().getFullYear()} Sociapa · Ads Dashboard
          </div>
        </div>
      </body>
      </html>
    `;

    // Configure transporter (Gmail in dev - uses env vars)
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL_USER || 'noreply@sociapa.com',
        pass: process.env.EMAIL_PASS || '',
      },
    });

    // In development, log instead of sending
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
      console.log('📧 Email report (dev mode - not actually sent):');
      console.log(`To: ${email}`);
      console.log(`Client: ${clientName} | Spend: ₹${totalSpend} | Clicks: ${totalClicks}`);
      return Response.json({
        success: true,
        message: 'Report generated (email not sent in dev mode - add EMAIL_USER and EMAIL_PASS to .env)',
        preview: { totalSpend, totalImpressions, totalClicks, totalConversions, ctr, cpc, cpm }
      });
    }

    await transporter.sendMail({
      from: `"Sociapa Ads Dashboard" <${process.env.EMAIL_USER}>`,
      to: email,
      subject: `${period.charAt(0).toUpperCase() + period.slice(1)} Ads Report - ${clientName}`,
      html,
    });

    return Response.json({ success: true, message: `Report sent to ${email}` });
  } catch (error) {
    console.error('Email report error:', error);
    return Response.json({ message: 'Failed to send report', error: error.message }, { status: 500 });
  }
}
